apiVersion: apps/v1kind: 
Deploymentmetadata:
  name: nginx-two-deploymentspec:  selector:    matchLabels:
      app: nginx-two
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-two
    spec:      containers:
      - name: nginx-two        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
        ---
       
apiVersion: v1
kind: Service
metadata:
  name: nginx-two
  labels:
    app: nginx-two
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: nginx-pod-port
    nodePort: 31112
    protocol: TCP
  selector:
####
##
# master $ kubectl create -f nginx.yaml
# deployment.apps/nginx-two-deployment created
# service/nginx-two created
